---
title: "Mappeinnlevering 2 sok-1005"
format: html
editor: visual
---

```{r}
# Installerer n??dvendige pakker hvis de ikke allerede er installert
install.packages("readr")
install.packages("dplyr")

# Laster inn n??dvendige pakker
library(readr)
library(dplyr)

# Angi filstiene til dataene
file_2022 <- "D:/skole/Nat2022us.zip"

# Leser inn dataene fra 2022
data_2022 <- read_fwf(
  file = file_2022,
  col_positions = fwf_positions(
    start = c(9, 13, 19, 23, 475, 504, 75, 149, 124, 163, 120, 171, 173, 255, 257, 259), # startposisjoner for hver kolonne
    end = c(12, 14, 22, 23, 475, 507, 76, 150, 124, 163, 120, 172, 174, 256, 258, 260) # sluttposisjoner for hver kolonne
  ),
 col_types = cols(
    X1 = col_integer(), # f??dsels??r
    X2 = col_integer(), # f??dselsm??ned
    X3 = col_integer(), # f??dselstidspunkt
    X4 = col_integer(), # f??dselsdag (ukedag)
    X5 = col_character(), # kj??nn
    X6 = col_double(), # f??dselsvekt
    X7 = col_integer(), # mors alder
    X8 = col_integer(), # fars alder
    X9 = col_character(), # mor utdannelse
    X10 = col_character(), # fars utdannelse
    X11 = col_character(), # mors sivilstatus
    X12 = col_character(), # levende tidligere f??dsel
    X13 = col_character(), # d??de tidligere f??dsler
    X14 = col_integer(), # antall sigaretter r??ykt i 1. trimester
    X15 = col_integer(), # antall sigaretter r??ykt i 2. trimester
    X16 = col_integer() # antall sigaretter r??ykt i 3. trimester
  )
)

# Endre navnene p?? kolonnene
data_2022 <- data_2022 %>%
  rename(
    Birth_year = X1,
    Birth_month = X2,
    Time_of_birth = X3,
    Day_of_birth = X4,
    Sex = X5,
    Birth_Weight_in_grams = X6,
    Age_of_mom = X7,
    Age_of_dad = X8,
    Mothers_Education = X9,
    Dads_Education = X10,
    Marital_status = X11,
    Prior_births_now_living = X12,
    Prior_births_now_dead = X13,
    Cigarettes_1ST_trimester = X14,
    Cigarettes_2ND_trimester = X15,
    Cigarettes_3RD_trimester = X16
  )
#Far sin sivilstatus var ikke i PDF filen, og er derfor ikke med.
#Birth_month er nummererte m??ned(1 = januar, 2 = februar osv)
#Day_of_birth er nummerert dag(1 = sC8ndag, 2 = mandag osv)
#Age_of_dad er nummerert hvor 1 = under 15 ??r, 2 = 15-19 ??r, og 3 = 20-24 ??r.
#Mothers_education og Dads_education er nummert hvor 1 = 8th grade or less,
# 2= 9th through 12th grade with no diploma, 5 = Associate degree (AA,AS) osv

```

```{r}
file_2004 <- "D:/skole/Nat2004us.zip"

# Leser inn dataene fra det gamle datasettet
data_2004 <- read_fwf(
  file = file_2004,
 col_positions = fwf_positions(
    start = c(15, 19, 29, 436, 463, 89, 186, 155, 153, 204, 206, 284, 286, 288), # Startposisjoner for hver kolonne
    end = c(18, 20, 29, 436, 466, 90, 187, 155, 153, 205, 207, 285, 287, 289) # Sluttposisjoner for hver kolonne
  ),
 col_types = cols(
    X1 = col_integer(), # f??dsels??r
    X2 = col_integer(), # f??dselsm??ned 
    # fC8dselstidspunkt
    X3 = col_integer(), # f??dselsdag (ukedag)
    X4 = col_character(), # kj??nn
    X5 = col_double(), # f??dselsvekt
    X6 = col_integer(), # mors alder
    X7 = col_integer(), # fars alder
    X8 = col_character(), # mor utdannelse
    #fars utdannelse
    X9 = col_character(), # mors sivilstatus
    #fars sivilstatus 
    X10 = col_character(),#f??rste f??dte som lever
    X11 = col_character(),#f??rstef??dte som er d??de
    X12 = col_integer(), # antall sigaretter r??ykt i 1. trimester
    X13 = col_integer(), # antall sigaretter r??ykt i 2. trimester
    X14 = col_integer() # antall sigaretter r??ykt i 3. trimester
  )
)

# Endre navnene p?? kolonnene
data_2004 <- data_2004 %>%
  rename(
    Birth_year = X1,
    Birth_month = X2,
    Day_of_birth = X3,
    Sex = X4,
    Birth_Weight_in_grams = X5,
    Age_of_mom = X6,
    Age_of_dad = X7,
    Mothers_Education = X8,
    Marital_status = X9,
    Prior_births_now_living = X10, 
    Prior_births_now_dead = X11, 
    Cigarettes_1ST_trimester = X12,
    Cigarettes_2ND_trimester = X13,
    Cigarettes_3RD_trimester = X14
  )



```

```{r}
# Sl??r sammen datasettene}
combined_data <- bind_rows(data_2022, data_2004)


```

```{r}
#Du skal lage en figur som viser fordelingen av f??dsler per m??ned. Du skal ogs?? legge til et informasjonslag som viser den relative fordelingen av f??dsler per m??ned


# Laster inn n??dvendige pakker
library(ggplot2)
library(dplyr)

ggplot(data = combined_data, aes(x = factor(Birth_month))) +
  geom_bar() +
  labs(title = "Distribution of Births per Month",
       x = "Month",
       y = "Number of Births") +
  scale_x_discrete(labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
  theme_minimal() +
   scale_y_continuous(labels = scales::comma)


```

```{r}
library(ggplot2)
library(dplyr)

# Lager et barplot for fordelingen av f??dsler per ukedag
ggplot(data = combined_data, aes(x = factor(Day_of_birth), fill = factor(Day_of_birth))) +
  geom_bar() +
  labs(title = "Distribution of Births by Day of Week",
       x = "Day of Week",
       y = "Number of Births") +
  scale_x_discrete(labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")) +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() +
     scale_y_continuous(labels = scales::comma)

```

```{r}


```

```{r}
library(ggplot2)
library(dplyr)

# Lager et barplot for fordelingen av f??dsler per tidspunkt p?? d??gnet
ggplot(data = combined_data, aes(x = Time_of_birth)) +
  geom_bar() +
  labs(title = "Distribution of Births by Time of Day",
       x = "Time of Day",
       y = "Number of Births") +
    scale_x_continuous(breaks = seq(0, 2400, by = 100),
                     labels = function(x) sprintf("%04d", x)) +
  theme_minimal()
```

```{r}
library(ggplot2)

# Lag et plott som viser fordelingen av f??dsler per alder p?? mor, med forskjellige farger for hver stolpe
ggplot(combined_data, aes(x = Age_of_mom, fill = factor(Age_of_mom))) +
  geom_bar() +
  labs(title = "Distribution of Births per Age of Mother",
       x = "Age of Mother",
       y = "Number of Births") +
  theme_minimal() +
     scale_y_continuous(labels = scales::comma)+
  scale_fill_discrete(name = "Age of Mother")

```

```{r}
# Laster inn n??dvendige pakker
library(ggplot2)
library(dplyr)

# Lager et barplot for fordelingen av f??dsler per alder p?? far
ggplot(data = combined_data, aes(x = Age_of_dad)) +
  geom_bar() +
  labs(title = "Distribution of Births by Father's Age",
       x = "Father's Age",
       y = "Number of Births") +
  scale_y_continuous(labels = scales::comma) +
  theme_minimal()
```

```{r}
# Installerer n??dvendige pakker hvis de ikke allerede er installert

# Laster inn n??dvendige pakker
library(ggplot2)
library(dplyr)

# Lager et s??ylediagram som viser gjennomsnittlig f??dselsvekt per kj??nn
ggplot(data = combined_data, aes(x = Sex, y = Birth_Weight_in_grams, fill = Sex)) +
  geom_bar(stat = "summary", fun = "mean") + 
  labs(title = "Average Birth Weight by Gender",
       x = "Sex",
       y = "Average Birth Weight (grams)") +
  theme_minimal()

```

Jeg vet at jeg ikke ble ferdig med oppgaven, som er min feil, men jeg har pr??vd og feilet i mange dager for ?? f?? til det jeg har av kode n??. Jeg slet virkelig med del 1, men det kom seg etter noen dager.
